# Generated by Django 6.0.3 on 2026-03-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("team_member_name", models.CharField(max_length=255)),
                ("team_member_status", models.CharField(max_length=100)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("job_status", models.CharField(max_length=100)),
                ("booked_date", models.DateField()),
                ("booked_end_date", models.DateField()),
                ("booked_start_time", models.TimeField()),
                ("booked_end_time", models.TimeField()),
                ("client_hourly_rate", models.FloatField()),
                ("credit_card_fee", models.FloatField(default=0)),
                ("rush_fee", models.FloatField(default=0)),
                ("gratuity", models.FloatField(default=0)),
                ("total_client_charge", models.FloatField(blank=True, null=True)),
                ("number_of_children", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
                ("client_confirm_notes", models.TextField(blank=True, null=True)),
                ("pet_selection", models.JSONField(default=list)),
                ("deposit_amount", models.FloatField(blank=True, null=True)),
                ("booking_fee", models.FloatField(default=0)),
                ("nanny_trial", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="Ai_app_book_created_8099bf_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="Ai_app_reco_created_548553_idx"
                    )
                ],
            },
        ),
    ]
