# Generated by Django 6.0.3 on 2026-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ai_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="ages_of_children",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="locations",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
