# Generated by Django 6.0.3 on 2026-03-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Ai_app", "0002_booking_ages_of_children_booking_locations"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booking",
            new_name="booking_created_f9a7e5_idx",
            old_name="Ai_app_book_created_8099bf_idx",
        ),
        migrations.AlterModelTable(
            name="booking",
            table="booking",
        ),
    ]
