# Generated by Django 6.0.3 on 2026-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Ai_app",
            "0003_rename_ai_app_book_created_8099bf_idx_booking_created_f9a7e5_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="booking_created_f9a7e5_idx",
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["city"], name="booking_city_794c26_idx"),
        ),
    ]
